# Generated by Django 3.2.14 on 2022-07-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userreg',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
